services:
    blackknight467.smarty_streets: '@blackknight467\SmartyStreetsBundle\Service\SmartyStreetsService'

    blackknight467\SmartyStreetsBundle\Service\SmartyStreetsService:
        arguments: ['%blackknight467_smartystreets.auth_id%', '%blackknight467_smartystreets.auth_token%']
